### ISSUE TITLE
Where are the .js files we need to run this?

### ISSUE THREAD

**Issue by answerquest** [vogdb/SelectLayersControl#2]
Hi, can you please provide some link or path to the .js files needed to run this thing? I included the files in /src and /dist and am getting error on console log:

```
TypeError: L.Control.ActiveLayers is undefined leaflet.select-layers.min.js:6
TypeError: L.control.selectLayers is not a function
```

**Comment by answerquest** [comment]
Don't bother.. found it here:
https://github.com/vogdb/Leaflet.ActiveLayers

Please specify this in the readme!

**Comment by vogdb** [comment]
Ok =) Will try to do it by Saturday.
