### ISSUE TITLE
Hide overlays panel if no overlays exist

### ISSUE THREAD

**Issue by almccon** [vogdb/SelectLayersControl#3]
Instead of this:

![screen shot 2015-08-04 at 5 41 42 pm](https://cloud.githubusercontent.com/assets/1212178/9075916/2377402e-3ad0-11e5-9bc9-54f4d9113175.png)

by default it should look like this when empty:

![screen shot 2015-08-04 at 5 42 27 pm](https://cloud.githubusercontent.com/assets/1212178/9075917/381f98e6-3ad0-11e5-8416-de902a61fc0d.png)

**Comment by vogdb** [comment]
Hi!
I'm afraid that this is a default browser representation of `<select multiple="true" style="width: 100%;"></select>` You can easily verify it on your browser.
Please share your propositions on the issue.
