### ISSUE TITLE
Mobile Browser can't collapsed control

### ISSUE THREAD

**Issue by bestpika** [vogdb/SelectLayersControl#4]
When I selected layer, the control could not collapsed.
(Android 5.1.1, Chrome)

**Comment by vogdb** [comment]
Hi @bestpika! Unfortunately I can't promise that I will be able to fix this soon. Have a lot on my plate now =( I think it's a good chance to contribute ;-)

**Comment by bestpika** [comment]
may be delete this can do it.
`,_collapse: function (e) { ... }`
